package io.github.certtool.reporting.core;

import io.github.certtool.domain.assessment.AssessmentFinding;
import io.github.certtool.domain.assessment.AssessmentStatus;
import io.github.certtool.reporting.ReportEnvelope;
import io.github.certtool.reporting.ReportSchema;
import io.github.certtool.reporting.SanitizationGuard;
import java.nio.charset.StandardCharsets;
import java.util.Map;
import java.util.Objects;

/**
 * Renders a {@link ReportEnvelope} to Markdown.
 *
 * <p>Suitable for diff-friendly storage in version control, paste into issue trackers, and
 * human inspection. Pipe characters and newlines in cell text are escaped via
 * {@link MarkdownEscaper}. After assembly the renderer runs {@link SanitizationGuard#enforce}.
 */
public final class MarkdownReportRenderer implements ReportRenderer {

    @Override
    public byte[] render(ReportEnvelope envelope) {
        Objects.requireNonNull(envelope, "envelope");

        StringBuilder sb = new StringBuilder(2048);
        sb.append("<!-- schema: ").append(envelope.schemaVersion()).append(" -->\n");
        sb.append("<!-- generator: ").append(envelope.toolName())
                .append(' ').append(envelope.toolVersion()).append(" -->\n");
        sb.append("# ").append(envelope.title()).append("\n\n");

        sb.append("- **Source:** `").append(envelope.sourceLabel()).append("`\n");
        sb.append("- **Generated:** `").append(envelope.generatedAt().toString()).append("`\n");
        sb.append("- **Tool:** `").append(envelope.toolName()).append(' ')
                .append(envelope.toolVersion()).append("`\n");
        sb.append("- **Schema:** `").append(envelope.schemaVersion()).append("`\n\n");

        appendSummary(sb, envelope);
        appendFindings(sb, envelope);
        if (envelope instanceof ReportEnvelope.ConversionReportEnvelope c) {
            appendConversion(sb, c);
        }
        appendDisclaimer(sb, envelope);

        String md = sb.toString();
        SanitizationGuard.enforce(md, envelope.title());
        return md.getBytes(StandardCharsets.UTF_8);
    }

    private static void appendSummary(StringBuilder sb, ReportEnvelope env) {
        sb.append("## Summary\n\n");
        Map<AssessmentStatus, Long> counts;
        if (env instanceof ReportEnvelope.AssessmentReportEnvelope a) {
            counts = a.counts();
        } else {
            counts = new java.util.EnumMap<>(AssessmentStatus.class);
            for (AssessmentStatus s : AssessmentStatus.values()) {
                counts.put(s, 0L);
            }
        }
        for (AssessmentStatus s : AssessmentStatus.values()) {
            sb.append("- ").append(s.name()).append(": ")
                    .append(counts.getOrDefault(s, 0L)).append('\n');
        }
        sb.append('\n');
    }

    private static void appendFindings(StringBuilder sb, ReportEnvelope env) {
        sb.append("## Findings\n\n");
        if (env.findings().isEmpty()) {
            sb.append("_No findings recorded._\n\n");
            return;
        }
        sb.append("| Rule | Title | Status | Severity | Summary | Evidence | Remediation | References |\n");
        sb.append("| --- | --- | --- | --- | --- | --- | --- | --- |\n");
        for (AssessmentFinding f : env.findings()) {
            sb.append("| ").append(MarkdownEscaper.escape(f.ruleId()))
                    .append(" | ").append(MarkdownEscaper.escape(f.title()))
                    .append(" | ").append(f.status().name())
                    .append(" | ").append(f.severity().name())
                    .append(" | ").append(MarkdownEscaper.escape(f.summary()))
                    .append(" | ").append(MarkdownEscaper.escape(f.evidence()))
                    .append(" | ").append(MarkdownEscaper.escape(f.remediation()))
                    .append(" | ").append(MarkdownEscaper.escape(String.join(", ", f.references())))
                    .append(" |\n");
        }
        sb.append('\n');
    }

    private static void appendConversion(StringBuilder sb, ReportEnvelope.ConversionReportEnvelope c) {
        sb.append("## Conversion Result\n\n");
        sb.append("- **Target:** `").append(c.targetPath()).append("`\n");
        sb.append("- **Written bytes:** ").append(c.writtenBytes()).append('\n');
        sb.append("- **Reload verified:** ").append(c.reloadVerified() ? "yes" : "no").append('\n');
        sb.append("- **Preflight codes:** ")
                .append(String.join(", ", c.preflightCodes())).append("\n\n");
    }

    private static void appendDisclaimer(StringBuilder sb, ReportEnvelope env) {
        sb.append("## Disclaimer\n\n");
        sb.append(env.disclaimer()).append("\n\n");
        sb.append("_Schema version: ").append(ReportSchema.REPORT_SCHEMA_VERSION)
                .append(" — generated by ").append(ReportSchema.TOOL_NAME)
                .append(' ').append(ReportSchema.TOOL_VERSION).append("._\n");
    }
}